env:
  CIRRUS_CLONE_DEPTH: 1

task:
  env:
    CFLAGS: -I /usr/local/include
    CXXFLAGS: -I/usr/local/include
    LDFLAGS: -L/usr/local/lib
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    platform: freebsd
  matrix:
    - name: 13.1-RELEASE
      compute_engine_instance:
        image: family/freebsd-13-1
    - name: 12.3-RELEASE
      compute_engine_instance:
        image: family/freebsd-12-3
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y autoconf automake asciidoc gmake libarchive libtool lzo2 pkgconf zstd
  script:
    - ./autogen.sh
    - ./configure --prefix=/usr/local
    - gmake -j`sysctl -n kern.smp.cpus`
    - gmake dist
