
all:
	if test -d ../../admin; then \
		rm -rf admin ;\
		cp -pRL ../../admin . ;\
	fi

	if ! test -d admin; then \
		echo "Need admin in ." ;\
		exit ;\
	fi
		
	rm -f configure.in.in
	ln -s configure.in.cvs configure.in.in
	$(MAKE) -f admin/Makefile.common cvs
